### ISSUE TITLE
Library seems to be targeting libminiz-2.1.0, while Native binaries provided are 2.2.0

### ISSUE THREAD

**Issue by Nickelony** [jsm174/net-miniz#8]
Trying to run this library, it seems to be looking for libminiz-2.1.0.dll, while the latest versions of NetMiniZ.Native are 2.2.0 instead.

EDIT:
It seems like an issue with the NetMiniZ NuGet package, the latest version of it is 1.2.2, while the Native binaries are 1.4.0.

**Comment by jsm174** [comment]
Hello. Are you using the following?

```
    <PackageReference Include="NetMiniZ" Version="1.4.0-preview.2" />
    <PackageReference Include="NetMiniZ.Native" Version="1.4.0" />
```

I know the version numbering is unfortunately a little strange.

**Comment by Nickelony** [comment]
> Hello. Are you using the following?
> 
> ```
>     <PackageReference Include="NetMiniZ" Version="1.4.0-preview.2" />
>     <PackageReference Include="NetMiniZ.Native" Version="1.4.0" />
> ```
> 
> I know the version numbering is unfortunately a little strange.

Yes, I just updated it to the preview version, I didn't have "Include prerelease" checked, so I didn't see it.
Now it works. :)

**Comment by jsm174** [comment]
G
